### ISSUE TITLE
🗄️ [Documentation] - How to manage credit cards

### ISSUE THREAD

**Issue by shall0pass** [rich-howell/actual-community-docs#35]
### Description

Detail a workflow and thought process of using credit cards with Actual.
1. Paying the card
2. Adding debt to the credit card to balance the budget in a month of over spending.
3. Adding transactions against a credit card.

edit:  I know this is covered briefly in the FAQ, but I think it's a budgeting topic that deserves some in depth explanation.

### Category

Budgeting

**Comment by rich-howell** [comment]
A good first branch was created #39 and merged for this.
