### ISSUE TITLE
🗄️ [Documentation] - Schedules

### ISSUE THREAD

**Issue by rich-howell** [rich-howell/actual-community-docs#7]
### Description

What are schedules, how do schedules work and what can they and can they not be used for. 

Repeated questions in Discord ask if they are customisable to certain days of the month on a repeat for example. 

Some documentation around how they work and how they don't work would be really helpful. 

### Category

Budgeting

**Comment by shall0pass** [comment]
I'll take a crack at this one if you'd like.

**Comment by rich-howell** [comment]
Thanks @shall0pass amazing first commit. Merged into main.
